
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - secrets.s1devops.com
  resources:
  - secretmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.s1devops.com
  resources:
  - secretmappings/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.s1devops.com
  resources:
  - secretmappings/status
  verbs:
  - get
  - patch
  - update
