# permissions for end users to view secretsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretsource-viewer-role
rules:
- apiGroups:
  - secrets.s1devops.com
  resources:
  - secretsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.s1devops.com
  resources:
  - secretsources/status
  verbs:
  - get
