# permissions for end users to edit secretsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretsource-editor-role
rules:
- apiGroups:
  - secrets.s1devops.com
  resources:
  - secretsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.s1devops.com
  resources:
  - secretsources/status
  verbs:
  - get
