# permissions for end users to edit secretmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretmapping-editor-role
rules:
- apiGroups:
  - secrets.s1devops.com
  resources:
  - secretmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.s1devops.com
  resources:
  - secretmappings/status
  verbs:
  - get
