# permissions for end users to view secretmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretmapping-viewer-role
rules:
- apiGroups:
  - secrets.s1devops.com
  resources:
  - secretmappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.s1devops.com
  resources:
  - secretmappings/status
  verbs:
  - get
