## Append samples you want in your CSV to this file as resources ##
resources:
- secrets_v1alpha1_secretmapping.yaml
- source.toolkit.fluxcd.io_v1beta1_gitrepository.yaml
- secrets_v1alpha1_secretsource.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
